repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
    rev: v0.3.2
    hooks:
    # Run the linter - Do not fail if errors are encountered
    # --no-fail -> Do not reject commit if unfixable errors are encountered
    - id: ruff
      args: [ --fix, --config, ../pyproject.toml, --no-fail ]
    # Run the formatter.
    - id: ruff-format
